import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/navigation';
import Footer from '@/components/Footer';
import { CartProviderClient, ShoppingCartSheet } from '@/components/cart/ui';

import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='ro'>
			<body className={nunito.className}>
				<CartProviderClient>
					<Navigation />
					<main className='max-w-6xl mx-auto px-8'>{children}</main>
					<ShoppingCartSheet />
					<Footer />
					<SpeedInsights />
					<Analytics />
				</CartProviderClient>
			</body>
		</html>
	);
}
