import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/navigation';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='ro'>
			<body className={nunito.className}>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
