import type { Metadata } from "next";
import Footer from "@/components/ui/Footer";
import { ShoppingCartSheet } from "@/components/cart/ui";

import { Analytics } from "@vercel/analytics/react";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navigation />
      <main className="max-w-6xl mx-auto px-8">{children}</main>
      <ShoppingCartSheet />
      <Footer />
      <Analytics />
    </>
  );
}
